### ISSUE TITLE
Hi, I'm trying to make an index page just like your site.

### ISSUE THREAD

**Issue by joshua7v** [oulvhai/mweb-medium-like#2]
It's almost done.
but
I have no idea about how to write a nav(like: previous page   next page) in page-index.html template
and how all.html works does not included in docs.

can I take a look at your page-index?  Thanks again.

**Comment by oulvhai** [comment]
hi, My blog http://coderforart.com don't has a page-index.html. The page-index.html template variables detail please check http://www.mweb.im/custom-site-theme-detail.html `build all pages template (Is page enable)` section.
