### ISSUE TITLE
关于加载更多

### ISSUE THREAD

**Issue by junyuyuan** [oulvhai/mweb-medium-like#3]
有些长博客会很长，请问是否有加载更多的功能？使每页的显示效果更好？

**Comment by junyuyuan** [comment]
类似于阅读全文按钮，然后主页上不完全显示每篇博客的内容。

**Comment by ysnows** [comment]
同问

**Comment by ysnows** [comment]
需要手动加入 这个标签

**Comment by oulvhai** [comment]
发现漏回信息了，抱歉！
如图：
![image](https://user-images.githubusercontent.com/2174294/32947875-18b795da-cbd8-11e7-866c-e64800fe570b.png)

**Comment by ysnows** [comment]
很棒；要是有个按钮，写完了文章，一键发送就好了^~^
